POST http://localhost:8080/api/meters
Content-Type: application/json

{
  "name": "gas",
  "type": "gas"
}

###
GET http://localhost:8080/api/meters
Accept: application/json

###
GET http://localhost:8080/api/meter-readings
Accept: application/json
